---
title: "tax_biplot"
output: github_document
date: "2024-06-12" original written by Madi Apgar
edited: "2025-09-03" edited by Laurie Lyon for use with Crestone data 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rmarkdown)
library(ggpubr)
library(ggplot2)
library(qiime2R)
library(tidyverse)
library(ggh4x)
library(viridis)
library(ggrepel)

setwd("~/Projects/crestone/laurie_crestone/scripts")
```

**Functions**
```{r}
prep_my_biplot_files <- function(biplot_fp,
                                 metadata_fp,
                                 tax_fp,
                                 parse_tax = TRUE,
                                 top_tax_n,
                                 dist_pc_axis,
                                 lines_longer_by){
  
  ## reading in file and extracting needed elements for plot
  pcoa_var <- read_qza(biplot_fp)$data$ProportionExplained
  ## for the points on plot
  biplot_points <- read_qza(biplot_fp)$data$Vectors
  ## for the lines w arrows on plot
  biplot_lines <- read_qza(biplot_fp)$data$Species
  
  ## metadata and taxonomy
  meta <- read_tsv(metadata_fp) %>% 
    mutate(abx_time = case_when(
      new_visit_num %in% c(1, 2) ~ "Screen, D1",
      new_visit_num %in% c(3) ~ "D4",
      new_visit_num %in% c(4) ~ "TOC",
      new_visit_num %in% c(5, 6, 7) ~ "D17, D40, D70", 
      .default = NA
      ),
      abx_time = factor(abx_time,
                        levels = c("Screen, D1", "D4", "TOC", "D17, D40, D70")
                        )
    )
  ##ADD STEP TO FILTER BY TREATMENT GROUP DURING WRANGLING ()
            #rename(sampleid = `#SampleID`)
  
  ifelse(parse_tax == TRUE, 
         taxonomy <- read_qza(tax_fp)$data %>% 
                      parse_taxonomy() %>%
                      rownames_to_column('asv'),
         taxonomy <- read_qza(tax_fp)$data %>% 
                      rename(asv = Feature.ID)
         )
  
  ##ADD SOMETHING HERE TO MERGE WITH METADATA AND SPLIT BY TREATMENT GROUP
  #
  ## some data wrangling wooo
  biplot_points <- biplot_points %>% 
                      rename(sampleid = SampleID) %>% 
                      select(sampleid, PC1, PC2, PC3, PC4) %>% 
                      right_join(meta, by = 'sampleid') #right join instead
  
  biplot_lines <- biplot_lines %>% 
                        mutate(dist_origin1to2 = sqrt(PC1^2 + PC2^2),
                               dist_origin2to3 = sqrt(PC2^2 + PC3^2),
                               dist_origin3to4 = sqrt(PC3^2 + PC4^2)) %>% 
                        slice_max(.data[[dist_pc_axis]], n = top_tax_n) %>% 
                        mutate(PC1 = (PC1 * 0.3)*lines_longer_by,
                               PC2 = (PC2 * 0.3)*lines_longer_by,
                               PC3 = (PC3 * 0.3)*lines_longer_by,
                               PC4 = (PC4 * 0.3)*lines_longer_by,) %>% 
                        rename(asv = FeatureID) %>% 
                        select(asv, PC1, PC2, PC3, PC4) %>% 
                        left_join(taxonomy, by = 'asv') 
  
  ## list of outputs
  my_list <- list(PCvar = pcoa_var,
                  DFPoints = biplot_points,
                  DFLines = biplot_lines,
                  Metadata = meta,
                  Taxonomy = taxonomy)
  return(my_list)
}

## takes the axis variance and makes it into a label for you so you don't
## have to do it every time 
pcoa_ax_lab <- function(unifrac_var, col_name){
  uni_lab <- as.character(round(unifrac_var[col_name] * 100, 2))
  uni_lab <- paste0(col_name, ' - ', uni_lab, '%')
  return(uni_lab)
}

#setting abx_levels and manual color palette for consistency with sIF_pcoa.Rmd
abx_levels <- c("Screen, D1", "D4", "TOC", "D17, D40, D70")

abx_palette <- viridis(
  n = length(abx_levels),
  option = "C",
  begin = 0,
  end = 0.95
)
names(abx_palette) <- abx_levels

## function for making the actual plot
make_my_biplot <- function(x_axis,
                           y_axis,
                           points_df,
                           points_color,
                           points_shape = NULL,
                           color_name,
                           shape_labels = NULL,
                           lines_df,
                           lines_label,
                           lines_label_size,
                           x_name,
                           y_name,
                           shape_name = NULL,
                           title_content){
  if(!is.null(points_shape)){
    plot <- ggplot() +
                  geom_jitter(data = points_df,
                             aes(x = .data[[x_axis]], y = .data[[y_axis]], 
                                 fill = .data[[points_color]],
                                 shape = .data[[points_shape]]),
                             size = 3.8,
                             alpha = 0.4, 
                             pch = 21) +
                scale_shape_discrete(labels = shape_labels) +
                labs(x = x_name,
                       y = y_name,
                       shape = shape_name,
                       title = title_content)
                
  } else {
         plot <- ggplot() +
                  geom_jitter(data = points_df,
                             aes(x = .data[[x_axis]], y = .data[[y_axis]], 
                                 fill = .data[[points_color]]),
                             size = 3.5,
                             alpha = 0.7, 
                             pch = 21) +
                  labs(x = x_name,
                       y = y_name,
                       title = title_content)
  }
  
  final_plot <- plot +
    scale_fill_manual(values = abx_palette, breaks = abx_levels, name = color_name) +
                  theme_bw(base_size = 16) +
                  geom_segment(data = lines_df,
                               aes(x = 0, xend = .data[[x_axis]], y = 0, yend = .data[[y_axis]]),
                               arrow = arrow(length = unit(0.2, "cm")), 
                               linewidth = 0.3) +
                  geom_text_repel(data = lines_df,
                                  aes(x = .data[[x_axis]], 
                                      y = .data[[y_axis]], 
                                      label = .data[[lines_label]]),
                                  color = 'black',
                                  size = lines_label_size,
                                  fontface = 'bold', 
                                  max.overlaps = 200)
  return(final_plot)
}
```


**File Paths**
```{r}
metadata_FP <- '../data/sif_sample_metadata.tsv'
#don't have this - was for blood CFUs for C.diff paper
#cfu_count_FP <- '../../oren_crestone/data/qiime/core_outputs/'
tax_FP <- '../../oren_crestone/data/qiime/taxonomy.qza'
#generated biplots using q_make_biplot_crs.sh
uu_biplot_FP <- '../data/qiime/core_outputs/crs_uu_biplot_matrix.qza'
wu_biplot_FP <- '../data/qiime/core_outputs/crs_wu_biplot_matrix.qza'

#vendor_labs <- c('Charles River',
                 #'Taconic')
treatment_labs <- c('CRS3123 200mg',
                    'CRS123 400mg', 
                    'Vancomycin 125mg')
# cfuCount_table <- read_tsv(cfu_count_FP) %>% 
#   select(mouse_id, location, microbe_presence) %>% 
#   spread(key = 'location', value = 'microbe_presence')
```

# **PC1 and PC2**
**Data Wrangling**
```{r}
## unweighted unifrac
uu_files <- prep_my_biplot_files(biplot_fp = uu_biplot_FP,
                                 metadata_fp = metadata_FP,
                                 tax_fp = tax_FP,
                                 parse_tax = TRUE,
                                 top_tax_n = 10,
                                 dist_pc_axis = 'dist_origin1to2',
                                 lines_longer_by = 4)

 uu_biplot_points <- uu_files$DFPoints %>% 
  mutate(new_visit_num = as.factor(new_visit_num))
#                       left_join(cfuCount_table, by = 'mouse_id') %>% 
#                       mutate(day_post_inf = as.factor(day_post_inf),
#                              spleen = as.factor(spleen),
#                              liver = as.factor(liver),
#                              blood = as.factor(blood)) %>% 
#                       na.omit()

#added code from Madi to label with Family if no assignment at Genus level 
uu_biplot_lines <- uu_files$DFLines %>%
  mutate(tax_line_label = ifelse(is.na(Species), Genus, Species),
         tax_line_label = ifelse(is.na(tax_line_label), Family, tax_line_label))

uu_pcoa_var <- uu_files$PCvar

## making x and y axis labels
uu_x_lab <- pcoa_ax_lab(unifrac_var = uu_pcoa_var,
                        col_name = 'PC1')
uu_y_lab <- pcoa_ax_lab(unifrac_var = uu_pcoa_var,
                        col_name = 'PC2')
```

```{r}
## weighted unifrac 
wu_files <- prep_my_biplot_files(biplot_fp = wu_biplot_FP,
                                 metadata_fp = metadata_FP,
                                 tax_fp = tax_FP,
                                 parse_tax = TRUE,
                                 top_tax_n = 10,
                                 dist_pc_axis = 'dist_origin1to2',
                                 lines_longer_by = 25)

wu_biplot_points <- wu_files$DFPoints %>% 
  mutate(new_visit_num = as.factor(new_visit_num))
#                       left_join(cfuCount_table, by = 'subject_id') %>% 
#                       mutate(day_post_inf = as.factor(day_post_inf),
#                              spleen = as.factor(spleen),
#                              liver = as.factor(liver),
#                              blood = as.factor(blood)) %>% 
#                       na.omit()

wu_biplot_lines <- wu_files$DFLines %>%
  mutate(tax_line_label = ifelse(is.na(Species), Genus, Species),
         tax_line_label = ifelse(is.na(tax_line_label), Family, tax_line_label))
wu_pcoa_var <- wu_files$PCvar

## making x and y axis labels
wu_x_lab <- pcoa_ax_lab(unifrac_var = wu_pcoa_var,
                        col_name = 'PC1')
wu_y_lab <- pcoa_ax_lab(unifrac_var = wu_pcoa_var,
                        col_name = 'PC2')
```
**Plots**
```{r, fig.width=8.5, fig.height=15}
## unweighted unifrac 
uu_biplot <- make_my_biplot(x_axis = 'PC1',
                            y_axis = 'PC2',
                            points_df = uu_biplot_points,
                            points_color = 'abx_time',
                            points_shape = 'treatment_group',
                            color_name = 'Visit Groupings',
                            shape_labels = treatment_labs,
                            lines_df = uu_biplot_lines,
                            lines_label = 'tax_line_label',
                            lines_label_size = 5,
                            x_name = uu_x_lab,
                            y_name = uu_y_lab,
                            shape_name = 'Treatment Group',
                            title_content = 'Unweighted UniFrac Biplot')

## weighted unifrac
wu_biplot <- make_my_biplot(x_axis = 'PC1',
                            y_axis = 'PC2',
                            points_df = wu_biplot_points,
                            points_color = 'abx_time',
                            points_shape = NULL,
                            color_name = 'Visit Groupings',
                            shape_labels = treatment_labs,
                            lines_df = wu_biplot_lines,
                            lines_label = 'tax_line_label',
                            lines_label_size = 5,
                            x_name = wu_x_lab,
                            y_name = wu_y_lab,
                            shape_name = 'Treatment Group',
                            title_content = 'Taxa Influencing Beta Diversity Distances (Weighted UniFrac)')
treat_labs <- c(
  CRS3123_200mg_po_bid = "CRS3123 200mg",
  CRS3123_400mg_po_bid = "CRS3123 400mg",
  Vancomycin_125mg_po_qid = "Vancomycin 125mg"
)

(uu_biplot_facet <- uu_biplot + 
  facet_wrap(~treatment_group,
             nrow = 3, 
             labeller = labeller(treatment_group = treat_labs)) +
  guides(shape = "none") +
  theme(legend.position = "top"))

(wu_biplot_facet <- wu_biplot +
  facet_wrap(~treatment_group,
             nrow = 3, 
             labeller = labeller(treatment_group = treat_labs)) +
  guides(shape = "none") +
  theme(legend.position = "top"))
```
```{r}
ggsave('../plots/wu_biplot1_2_facet.png',
       plot = wu_biplot_facet,
       width = 6.5,
       height = 15)
ggsave('../plots/wu_biplot1_2_facet.pdf',
       plot = wu_biplot_facet,
       width = 6.5,
       height = 15)
save(wu_biplot_facet, file = "../../figures/fig_3a_wu_biplot.rdat")
```

# **PC2 and PC3**
**Data Wrangling**
```{r}
## unweighted unifrac
uu_files2_3 <- prep_my_biplot_files(biplot_fp = uu_biplot_FP,
                                 metadata_fp = metadata_FP,
                                 tax_fp = tax_FP,
                                 parse_tax = TRUE,
                                 top_tax_n = 20,
                                 dist_pc_axis = 'dist_origin2to3',
                                 lines_longer_by = 4)

uu_biplot_points2_3 <- uu_files2_3$DFPoints %>%
                      mutate(new_visit_num = as.factor(new_visit_num))

uu_biplot_lines2_3 <- uu_files2_3$DFLines %>%
  mutate(tax_line_label = ifelse(is.na(Species), Genus, Species),
         tax_line_label = ifelse(is.na(tax_line_label), Family, tax_line_label))

uu_pcoa_var2_3 <- uu_files2_3$PCvar

## making x and y axis labels
uu_x_lab2_3 <- pcoa_ax_lab(unifrac_var = uu_pcoa_var2_3,
                           col_name = 'PC2')
uu_y_lab2_3 <- pcoa_ax_lab(unifrac_var = uu_pcoa_var2_3,
                           col_name = 'PC3')
```

```{r}
## weighted unifrac 
wu_files2_3 <- prep_my_biplot_files(biplot_fp = wu_biplot_FP,
                                   metadata_fp = metadata_FP,
                                   tax_fp = tax_FP,
                                   parse_tax = TRUE,
                                   top_tax_n = 20,
                                   dist_pc_axis = 'dist_origin2to3',
                                   lines_longer_by = 9)

wu_biplot_points2_3 <- wu_files2_3$DFPoints %>% 
  mutate(new_visit_num = as.factor(new_visit_num))

wu_biplot_lines2_3 <- wu_files2_3$DFLines %>%
  mutate(tax_line_label = ifelse(is.na(Species), Genus, Species),
         tax_line_label = ifelse(is.na(tax_line_label), Family, tax_line_label))

wu_pcoa_var2_3 <- wu_files2_3$PCvar

## making x and y axis labels
wu_x_lab2_3 <- pcoa_ax_lab(unifrac_var = wu_pcoa_var2_3,
                           col_name = 'PC2')
wu_y_lab2_3 <- pcoa_ax_lab(unifrac_var = wu_pcoa_var2_3,
                           col_name = 'PC3')
```

**Plots**
```{r, fig.width=20, fig.height=8}
## unweighted unifrac 
uu_biplot2_3 <- make_my_biplot(x_axis = 'PC2',
                              y_axis = 'PC3',
                              points_df = uu_biplot_points2_3,
                              points_color = 'abx_time',
                              points_shape = 'treatment_group',
                              color_name = 'Visit',
                              shape_labels = treatment_labs,
                              lines_df = uu_biplot_lines2_3,
                              lines_label = 'tax_line_label',
                              lines_label_size = 5,
                              x_name = uu_x_lab2_3,
                              y_name = uu_y_lab2_3,
                              shape_name = 'Treatment',
                              title_content = 'Unweighted UniFrac Biplot (PC2-PC3)')

## weighted unifrac
wu_biplot2_3 <- make_my_biplot(x_axis = 'PC2',
                              y_axis = 'PC3',
                              points_df = wu_biplot_points2_3,
                              points_color = 'abx_time',
                              points_shape = 'treatment_group',
                              color_name = 'Visit',
                              shape_labels = treatment_labs,
                              lines_df = wu_biplot_lines2_3,
                              lines_label = 'tax_line_label',
                              lines_label_size = 5,
                              x_name = wu_x_lab2_3,
                              y_name = wu_y_lab2_3,
                              shape_name = 'Treatment',
                              title_content = 'Weighted UniFrac Biplot (PC2-PC3)')

uu_biplot2_3
wu_biplot2_3
```


**Plots**
```{r, fig.width=15, fig.height=10}
## unweighted unifrac 
uu_biplot3_4 <- make_my_biplot(x_axis = 'PC3',
                              y_axis = 'PC4',
                              points_df = uu_biplot_points3_4,
                              points_color = 'day_post_inf',
                              points_shape = 'vendor',
                              color_name = 'Days Relative\nto Infection',
                              shape_labels = vendor_labs,
                              lines_df = uu_biplot_lines3_4,
                              lines_label = 'Family',
                              lines_label_size = 5,
                              x_name = uu_x_lab3_4,
                              y_name = uu_y_lab3_4,
                              shape_name = 'Vendor',
                              title_content = 'Unweighted UniFrac Biplot (PC3-PC4)')

## weighted unifrac
wu_biplot3_4 <- make_my_biplot(x_axis = 'PC3',
                              y_axis = 'PC4',
                              points_df = wu_biplot_points3_4,
                              points_color = 'day_post_inf',
                              points_shape = 'vendor',
                              color_name = 'Days Relative\nto Infection',
                              shape_labels = vendor_labs,
                              lines_df = wu_biplot_lines3_4,
                              lines_label = 'Family',
                              lines_label_size = 5,
                              x_name = wu_x_lab3_4,
                              y_name = wu_y_lab3_4,
                              shape_name = 'Vendor',
                              title_content = 'Weighted UniFrac Biplot (PC3-PC4)')

uu_biplot3_4
wu_biplot3_4
```

# **Saving my Outputs**

```{r}
ggsave('../plots/uu_biplot1_2.pdf',
       plot = uu_biplot,
       width = 15,
       height = 10)
ggsave('../plots/wu_biplot1_2.pdf',
       plot = wu_biplot,
       width = 15,
       height = 10)
ggsave('../plots/uu_biplot2_3.pdf',
       plot = uu_biplot2_3,
       width = 15,
       height = 10)
ggsave('../plots/wu_biplot2_3.pdf',
       plot = wu_biplot2_3,
       width = 15,
       height = 10)
```
